//! Boundary-representation kernel: topological types and the modeling context arena.
//!
//! This module contains the topological layer of the B-rep kernel. Geometric types
//! (points, curves, surfaces) live in [`crate::geom`]. The two layers are intentionally
//! separate: topology describes *connectivity*; geometry describes *shape*.
//!
//! # Arena model
//! All entities are owned by a [`SolidModelingContext`], which stores them in typed
//! `Vec`s. Every entity type has a corresponding newtype ID (e.g. [`VertexId`]) that is
//! an index into the relevant `Vec`. IDs are stable as long as no element is removed;
//! removal is not supported in Phase 3.
//!
//! # Naming
//! Arena accessor methods follow the pattern `push_<type>` / `get_<type>` /
//! `get_mut_<type>`, generated by the `impl_push_get!` macro.

use std::sync::Arc;
use smallvec::SmallVec;

use crate::geom::{Point3, Curve3Kind, Curve2Kind, SurfaceKind};
use crate::csg_lang::CsgMetadata;

// ── Newtype ID macro ──────────────────────────────────────────────────────────

macro_rules! define_id {
    ($name:ident) => {
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        pub struct $name(pub usize);
    };
}

define_id!(VertexId);
define_id!(EdgeId);
define_id!(CoEdgeId);
define_id!(LoopId);
define_id!(FaceId);
define_id!(ShellId);
define_id!(SolidId);
define_id!(NodeBRepId);
define_id!(SurfaceId);
define_id!(Curve3Id);
define_id!(Curve2Id);
define_id!(AttrId);

// ── Support types ─────────────────────────────────────────────────────────────

/// Whether the outward face normal is aligned with or opposite to the surface's
/// natural normal (`normalize(∂S/∂u × ∂S/∂v)`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FaceSense {
    Aligned,
    AntiAligned,
}

/// Whether a coedge traverses its underlying edge in the forward (increasing `t`)
/// or reverse direction.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Orientation {
    Forward,
    Reverse,
}

/// The CSG boolean operation that produced a face (used in provenance tracking).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OpType {
    Union,
    Difference,
    Intersection,
}

/// A reference back to the CSG primitive that originally contributed a face.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CsgSource {
    /// `prov_id` of the originating [`CsgNode`](crate::csg_lang::CsgNode).
    pub prov_id: u64,
    /// `geom_id` of the originating [`CsgNode`](crate::csg_lang::CsgNode).
    pub geom_id: u64,
}

impl CsgSource {
    pub fn new(prov_id: u64, geom_id: u64) -> Self {
        Self { prov_id, geom_id }
    }
}

/// Tracks where a face came from in the CSG tree.
///
/// A primitive face has one source and no `last_op`. A coincident face after a union
/// may have two sources. A face produced by a boolean intersection has two sources and
/// `last_op` set to the operation.
#[derive(Debug, Clone, PartialEq)]
pub struct ProvenanceData {
    pub sources: SmallVec<[CsgSource; 1]>,
    pub last_op: Option<OpType>,
}

impl ProvenanceData {
    /// Convenience constructor for a face that comes directly from a single CSG
    /// primitive (the common case).
    pub fn primitive(prov_id: u64, geom_id: u64) -> Self {
        Self {
            sources: SmallVec::from_buf([CsgSource::new(prov_id, geom_id)]),
            last_op: None,
        }
    }
}

/// Kernel-wide tolerances stored in the [`SolidModelingContext`].
///
/// Applied during vertex snapping, normal comparisons, and parametric proximity
/// checks. Not stored per-node — all operations in a context share one tolerance.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct KernelTolerance {
    /// Positional tolerance for vertex snapping (metres for mm-scale models ≈ 1e-7).
    pub pos_tol: f64,
    /// Angular tolerance in radians.
    pub ang_tol: f64,
    /// Parametric proximity tolerance for curve/surface evaluation.
    pub param_tol: f64,
}

impl Default for KernelTolerance {
    fn default() -> Self {
        Self { pos_tol: 1e-7, ang_tol: 1e-9, param_tol: 1e-10 }
    }
}

// ── Topological structs ───────────────────────────────────────────────────────

/// A geometric vertex: a 3-D point with an associated snapping tolerance.
#[derive(Debug, Clone, PartialEq)]
pub struct Vertex {
    pub point: Point3,
    /// Per-vertex snapping tolerance; typically equals `KernelTolerance::pos_tol`.
    pub tol: f64,
}

impl Vertex {
    pub fn new(point: Point3, tol: f64) -> Self {
        Self { point, tol }
    }
}

/// A trimmed curve connecting two vertices.
///
/// `coedges` starts empty and is populated as coedges referencing this edge are added
/// to the B-rep. A manifold edge has exactly two coedges (one per adjacent face); during
/// boolean intermediate steps more than two may be present temporarily.
///
/// Degenerate edges (`v0 == v1`, curve evaluates to a constant point) represent the
/// poles of a sphere or the apex of a cone. See `brep_notes.md`.
#[derive(Debug, Clone, PartialEq)]
pub struct Edge {
    pub curve3:  Curve3Id,
    pub v0:      VertexId,
    pub v1:      VertexId,
    /// Parameter value such that `curve3.eval(t0)` gives the position of `v0`.
    pub t0:      f64,
    /// Parameter value such that `curve3.eval(t1)` gives the position of `v1`.
    pub t1:      f64,
    pub coedges: SmallVec<[CoEdgeId; 2]>,
}

impl Edge {
    pub fn new(curve3: Curve3Id, v0: VertexId, v1: VertexId, t0: f64, t1: f64) -> Self {
        Self { curve3, v0, v1, t0, t1, coedges: SmallVec::new() }
    }
}

/// An oriented use of an [`Edge`] by a [`Face`].
///
/// The `pcurve` is the image of this coedge in the UV parameter space of the containing
/// face's surface. Its orientation matches the 3-D curve: if `orientation` is `Forward`,
/// the pcurve runs in the direction of increasing `t`.
#[derive(Debug, Clone, PartialEq)]
pub struct CoEdge {
    pub edge:        EdgeId,
    pub orientation: Orientation,
    pub face:        FaceId,
    pub pcurve:      Curve2Id,
}

impl CoEdge {
    pub fn new(edge: EdgeId, orientation: Orientation, face: FaceId, pcurve: Curve2Id) -> Self {
        Self { edge, orientation, face, pcurve }
    }
}

/// An ordered, closed sequence of [`CoEdge`]s bounding a region of a [`Face`].
///
/// `coedges` starts empty and is populated in order; the invariant is that the end
/// vertex of each coedge equals the start vertex of the next, and the last coedge's end
/// equals the first's start.
#[derive(Debug, Clone, PartialEq)]
pub struct Loop {
    pub coedges:  Vec<CoEdgeId>,
    pub face:     FaceId,
    pub is_outer: bool,
}

impl Loop {
    pub fn new(face: FaceId, is_outer: bool) -> Self {
        Self { coedges: Vec::new(), face, is_outer }
    }
}

/// A trimmed parametric surface bounded by one outer loop and zero or more inner loops
/// (holes).
///
/// `attr` is `None` at construction and may be set later to attach colour/material data.
#[derive(Debug, Clone, PartialEq)]
pub struct Face {
    pub shell:   ShellId,
    pub surface: SurfaceId,
    pub outer:   LoopId,
    pub inners:  Vec<LoopId>,
    pub sense:   FaceSense,
    pub prov:    ProvenanceData,
    pub attr:    Option<AttrId>,
}

impl Face {
    pub fn new(
        shell:   ShellId,
        surface: SurfaceId,
        outer:   LoopId,
        sense:   FaceSense,
        prov:    ProvenanceData,
    ) -> Self {
        Self { shell, surface, outer, inners: Vec::new(), sense, prov, attr: None }
    }
}

/// A connected, orientable collection of [`Face`]s forming a single closed surface.
///
/// `faces` starts empty and is populated as faces are added to the B-rep.
#[derive(Debug, Clone, PartialEq)]
pub struct Shell {
    pub solid:    SolidId,
    pub faces:    Vec<FaceId>,
    pub is_outer: bool,
}

impl Shell {
    pub fn new(solid: SolidId, is_outer: bool) -> Self {
        Self { solid, faces: Vec::new(), is_outer }
    }
}

/// A single connected solid: one outer shell and zero or more inner shells (voids).
#[derive(Debug, Clone, PartialEq)]
pub struct Solid {
    pub outer:  ShellId,
    pub inners: Vec<ShellId>,
}

impl Solid {
    pub fn new(outer: ShellId) -> Self {
        Self { outer, inners: Vec::new() }
    }
}

/// The B-rep result of evaluating a single CSG node.
///
/// A CSG node may produce zero solids (empty result) or more than one (disconnected
/// components from a boolean operation). `solids` starts empty and is populated during
/// B-rep compilation.
#[derive(Debug, Clone, PartialEq)]
pub struct NodeBRep {
    pub solids:        Vec<SolidId>,
    pub source_csg_id: u64,
}

impl NodeBRep {
    pub fn new(source_csg_id: u64) -> Self {
        Self { solids: Vec::new(), source_csg_id }
    }
}

// ── Arena macro ───────────────────────────────────────────────────────────────

/// Generate `push_<name>`, `get_<name>`, and `get_mut_<name>` methods on
/// `SolidModelingContext` for one entity type.
macro_rules! impl_push_get {
    ($vec:ident, $id:ident, $item:ty, $push:ident, $get:ident, $get_mut:ident) => {
        pub fn $push(&mut self, item: $item) -> $id {
            let id = $id(self.$vec.len());
            self.$vec.push(item);
            id
        }
        pub fn $get(&self, id: $id) -> &$item {
            &self.$vec[id.0]
        }
        pub fn $get_mut(&mut self, id: $id) -> &mut $item {
            &mut self.$vec[id.0]
        }
    };
}

// ── SolidModelingContext ──────────────────────────────────────────────────────

/// The central arena that owns all B-rep entities.
///
/// All geometry and topology is stored in typed `Vec`s. Entity IDs are indices into
/// these `Vec`s and remain stable as long as no element is removed. Operations within
/// the context share a single [`KernelTolerance`].
pub struct SolidModelingContext {
    pub surfaces:   Vec<SurfaceKind>,
    pub curves3:    Vec<Curve3Kind>,
    pub curves2:    Vec<Curve2Kind>,
    pub nodes:      Vec<NodeBRep>,
    pub solids:     Vec<Solid>,
    pub shells:     Vec<Shell>,
    pub faces:      Vec<Face>,
    pub loops:      Vec<Loop>,
    pub coedges:    Vec<CoEdge>,
    pub edges:      Vec<Edge>,
    pub vertices:   Vec<Vertex>,
    pub attributes: Vec<Arc<CsgMetadata>>,
    pub tolerance:  KernelTolerance,
}

impl SolidModelingContext {
    /// Create an empty context with default kernel tolerances.
    pub fn new() -> Self {
        Self {
            surfaces:   Vec::new(),
            curves3:    Vec::new(),
            curves2:    Vec::new(),
            nodes:      Vec::new(),
            solids:     Vec::new(),
            shells:     Vec::new(),
            faces:      Vec::new(),
            loops:      Vec::new(),
            coedges:    Vec::new(),
            edges:      Vec::new(),
            vertices:   Vec::new(),
            attributes: Vec::new(),
            tolerance:  KernelTolerance::default(),
        }
    }

    impl_push_get!(surfaces,   SurfaceId,   SurfaceKind,  push_surface,   get_surface,   get_mut_surface);
    impl_push_get!(curves3,    Curve3Id,    Curve3Kind,   push_curve3,    get_curve3,    get_mut_curve3);
    impl_push_get!(curves2,    Curve2Id,    Curve2Kind,   push_curve2,    get_curve2,    get_mut_curve2);
    impl_push_get!(nodes,      NodeBRepId,  NodeBRep,     push_node,      get_node,      get_mut_node);
    impl_push_get!(solids,     SolidId,     Solid,        push_solid,     get_solid,     get_mut_solid);
    impl_push_get!(shells,     ShellId,     Shell,        push_shell,     get_shell,     get_mut_shell);
    impl_push_get!(faces,      FaceId,      Face,         push_face,      get_face,      get_mut_face);
    impl_push_get!(loops,      LoopId,      Loop,         push_loop,      get_loop,      get_mut_loop);
    impl_push_get!(coedges,    CoEdgeId,    CoEdge,       push_coedge,    get_coedge,    get_mut_coedge);
    impl_push_get!(edges,      EdgeId,      Edge,         push_edge,      get_edge,      get_mut_edge);
    impl_push_get!(vertices,   VertexId,    Vertex,       push_vertex,    get_vertex,    get_mut_vertex);
    impl_push_get!(attributes, AttrId,      Arc<CsgMetadata>, push_attr,  get_attr,      get_mut_attr);
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod test {
    use super::*;
    use crate::geom::{Point3, Line3, Line2, Plane, Curve3Kind, Curve2Kind, SurfaceKind};

    fn pt(x: f64, y: f64, z: f64) -> Point3 { Point3::new(x, y, z) }

    fn minimal_ctx() -> SolidModelingContext { SolidModelingContext::new() }

    // ── Newtype IDs ───────────────────────────────────────────────────────────

    #[test]
    fn id_equality() {
        assert_eq!(VertexId(0), VertexId(0));
        assert_ne!(VertexId(0), VertexId(1));
    }

    #[test]
    fn id_copy() {
        let a = EdgeId(3);
        let b = a;          // Copy — both remain valid
        assert_eq!(a, b);
    }

    // ── Support types ─────────────────────────────────────────────────────────

    #[test]
    fn face_sense_eq() {
        assert_eq!(FaceSense::Aligned, FaceSense::Aligned);
        assert_ne!(FaceSense::Aligned, FaceSense::AntiAligned);
    }

    #[test]
    fn orientation_eq() {
        assert_eq!(Orientation::Forward, Orientation::Forward);
        assert_ne!(Orientation::Forward, Orientation::Reverse);
    }

    #[test]
    fn op_type_eq() {
        assert_eq!(OpType::Union, OpType::Union);
        assert_ne!(OpType::Union, OpType::Difference);
    }

    #[test]
    fn csg_source_stores_fields() {
        let s = CsgSource::new(42, 99);
        assert_eq!(s.prov_id, 42);
        assert_eq!(s.geom_id, 99);
    }

    #[test]
    fn provenance_primitive_one_source_no_op() {
        let prov = ProvenanceData::primitive(1, 2);
        assert_eq!(prov.sources.len(), 1);
        assert_eq!(prov.sources[0].prov_id, 1);
        assert_eq!(prov.sources[0].geom_id, 2);
        assert_eq!(prov.last_op, None);
    }

    #[test]
    fn kernel_tolerance_defaults() {
        let t = KernelTolerance::default();
        assert_eq!(t.pos_tol,   1e-7);
        assert_eq!(t.ang_tol,   1e-9);
        assert_eq!(t.param_tol, 1e-10);
    }

    // ── Topological struct construction ───────────────────────────────────────

    #[test]
    fn vertex_new_stores_fields() {
        let v = Vertex::new(pt(1.0, 2.0, 3.0), 1e-7);
        assert_eq!(v.point, pt(1.0, 2.0, 3.0));
        assert_eq!(v.tol, 1e-7);
    }

    #[test]
    fn edge_new_stores_fields_coedges_empty() {
        let e = Edge::new(Curve3Id(0), VertexId(0), VertexId(1), 0.0, 1.0);
        assert_eq!(e.curve3, Curve3Id(0));
        assert_eq!(e.v0, VertexId(0));
        assert_eq!(e.v1, VertexId(1));
        assert_eq!(e.t0, 0.0);
        assert_eq!(e.t1, 1.0);
        assert!(e.coedges.is_empty());
    }

    #[test]
    fn coedge_new_stores_fields() {
        let ce = CoEdge::new(EdgeId(0), Orientation::Forward, FaceId(0), Curve2Id(0));
        assert_eq!(ce.edge, EdgeId(0));
        assert_eq!(ce.orientation, Orientation::Forward);
        assert_eq!(ce.face, FaceId(0));
        assert_eq!(ce.pcurve, Curve2Id(0));
    }

    #[test]
    fn loop_new_stores_fields_coedges_empty() {
        let l = Loop::new(FaceId(2), true);
        assert_eq!(l.face, FaceId(2));
        assert!(l.is_outer);
        assert!(l.coedges.is_empty());
    }

    #[test]
    fn face_new_stores_fields_inners_empty_attr_none() {
        let prov = ProvenanceData::primitive(1, 2);
        let f = Face::new(ShellId(0), SurfaceId(0), LoopId(0), FaceSense::Aligned, prov.clone());
        assert_eq!(f.shell,   ShellId(0));
        assert_eq!(f.surface, SurfaceId(0));
        assert_eq!(f.outer,   LoopId(0));
        assert_eq!(f.sense,   FaceSense::Aligned);
        assert_eq!(f.prov,    prov);
        assert!(f.inners.is_empty());
        assert!(f.attr.is_none());
    }

    #[test]
    fn shell_new_stores_fields_faces_empty() {
        let s = Shell::new(SolidId(0), true);
        assert_eq!(s.solid, SolidId(0));
        assert!(s.is_outer);
        assert!(s.faces.is_empty());
    }

    #[test]
    fn solid_new_stores_outer_inners_empty() {
        let s = Solid::new(ShellId(0));
        assert_eq!(s.outer, ShellId(0));
        assert!(s.inners.is_empty());
    }

    #[test]
    fn nodebrep_new_stores_csg_id_solids_empty() {
        let n = NodeBRep::new(42);
        assert_eq!(n.source_csg_id, 42);
        assert!(n.solids.is_empty());
    }

    // ── Arena round-trips ─────────────────────────────────────────────────────

    #[test]
    fn arena_vertex_push_get_roundtrip() {
        let mut ctx = minimal_ctx();
        let id0 = ctx.push_vertex(Vertex::new(pt(0.0, 0.0, 0.0), 1e-7));
        let id1 = ctx.push_vertex(Vertex::new(pt(1.0, 0.0, 0.0), 1e-7));
        assert_eq!(id0, VertexId(0));
        assert_eq!(id1, VertexId(1));
        assert_eq!(ctx.get_vertex(id0).point, pt(0.0, 0.0, 0.0));
        assert_eq!(ctx.get_vertex(id1).point, pt(1.0, 0.0, 0.0));
    }

    #[test]
    fn arena_vertex_get_mut_modifies() {
        let mut ctx = minimal_ctx();
        let id = ctx.push_vertex(Vertex::new(pt(0.0, 0.0, 0.0), 1e-7));
        ctx.get_mut_vertex(id).point = pt(9.0, 9.0, 9.0);
        assert_eq!(ctx.get_vertex(id).point, pt(9.0, 9.0, 9.0));
    }

    #[test]
    fn arena_edge_push_get_roundtrip() {
        let mut ctx = minimal_ctx();
        let id = ctx.push_edge(Edge::new(Curve3Id(0), VertexId(0), VertexId(1), 0.0, 1.0));
        assert_eq!(id, EdgeId(0));
        assert_eq!(ctx.get_edge(id).v1, VertexId(1));
    }

    #[test]
    fn arena_face_push_get_roundtrip() {
        let mut ctx = minimal_ctx();
        let prov = ProvenanceData::primitive(1, 2);
        let id = ctx.push_face(Face::new(
            ShellId(0), SurfaceId(0), LoopId(0), FaceSense::AntiAligned, prov,
        ));
        assert_eq!(id, FaceId(0));
        assert_eq!(ctx.get_face(id).sense, FaceSense::AntiAligned);
    }

    #[test]
    fn arena_surface_push_get_roundtrip() {
        let mut ctx = minimal_ctx();
        let plane = Plane::new(pt(0.0, 0.0, 0.0), pt(1.0, 0.0, 0.0), pt(0.0, 1.0, 0.0));
        let id = ctx.push_surface(SurfaceKind::Plane(plane));
        assert_eq!(id, SurfaceId(0));
        // Verify it round-trips: can get_surface without panic
        let _ = ctx.get_surface(id);
    }

    #[test]
    fn arena_curve3_push_get_roundtrip() {
        let mut ctx = minimal_ctx();
        let line = Line3::new(pt(0.0, 0.0, 0.0), pt(1.0, 0.0, 0.0));
        let id = ctx.push_curve3(Curve3Kind::Line3(line));
        assert_eq!(id, Curve3Id(0));
        let _ = ctx.get_curve3(id);
    }

    #[test]
    fn arena_ids_increment_per_type() {
        let mut ctx = minimal_ctx();
        let v0 = ctx.push_vertex(Vertex::new(pt(0.0, 0.0, 0.0), 1e-7));
        let v1 = ctx.push_vertex(Vertex::new(pt(1.0, 0.0, 0.0), 1e-7));
        let e0 = ctx.push_edge(Edge::new(Curve3Id(0), v0, v1, 0.0, 1.0));
        let e1 = ctx.push_edge(Edge::new(Curve3Id(0), v0, v1, 0.0, 1.0));
        // Vertex and Edge IDs are independent sequences
        assert_eq!(v0, VertexId(0));
        assert_eq!(v1, VertexId(1));
        assert_eq!(e0, EdgeId(0));
        assert_eq!(e1, EdgeId(1));
    }
}
