// Phase-0 staging: the b-rep kernel structs and Context side-tables are not yet
// wired into the public Python API. Phase 0-c migrates them to defining-only structs
// with Context side-tables; remove this allow once the kernel is wired up.
#![allow(dead_code)]

//! Boundary-representation kernel: topological types and the modeling context arena.
//!
//! This module contains the topological layer of the B-rep kernel. Geometric types
//! (points, curves, surfaces) live in [`crate::geom`]. The two layers are intentionally
//! separate: topology describes *connectivity*; geometry describes *shape*.
//!
//! # Arena model
//! All entities are owned by a [`SolidModelingContext`], which stores them in typed
//! `Vec`s. Every entity type has a corresponding newtype ID (e.g. [`VertexId`]) that is
//! an index into the relevant `Vec`. IDs are stable as long as no element is removed;
//! removal is not supported in Phase 3.
//!
//! # Naming
//! Arena accessor methods follow the pattern `push_<type>` / `get_<type>` /
//! `get_mut_<type>`, generated by the `impl_push_get!` macro.

use smallvec::SmallVec;
use std::collections::HashMap;
use std::sync::Arc;

use crate::csg_lang::CsgMetadata;
use crate::geom::{Curve2Kind, Curve3Kind, Point3, SurfaceKind};

// ── Newtype ID macro ──────────────────────────────────────────────────────────

macro_rules! define_id {
    ($name:ident) => {
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        pub struct $name(pub usize);
    };
}

define_id!(VertexId);
define_id!(EdgeId);
define_id!(CoEdgeId);
define_id!(LoopId);
define_id!(FaceId);
define_id!(ShellId);
define_id!(SolidId);
define_id!(SolidSetId);
define_id!(SurfaceId);
define_id!(Curve3Id);
define_id!(Curve2Id);
define_id!(AttrId);

// ── Support types ─────────────────────────────────────────────────────────────

/// Whether the outward face normal is aligned with or opposite to the surface's
/// natural normal (`normalize(∂S/∂u × ∂S/∂v)`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FaceSense {
    Aligned,
    AntiAligned,
}

/// Whether a coedge traverses its underlying edge in the forward (increasing `t`)
/// or reverse direction.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Orientation {
    Forward,
    Reverse,
}

/// The CSG boolean operation that produced a face (used in provenance tracking).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OpType {
    Union,
    Difference,
    Intersection,
}

/// A reference back to the CSG primitive that originally contributed a face.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CsgSource {
    /// `prov_id` of the originating [`CsgNode`](crate::csg_lang::CsgNode).
    pub prov_id: u64,
    /// `geom_id` of the originating [`CsgNode`](crate::csg_lang::CsgNode).
    pub geom_id: u64,
}

impl CsgSource {
    pub fn new(prov_id: u64, geom_id: u64) -> Self {
        Self { prov_id, geom_id }
    }
}

/// Tracks where a face came from in the CSG tree.
///
/// A primitive face has one source and no `last_op`. A coincident face after a union
/// may have two sources. A face produced by a boolean intersection has two sources and
/// `last_op` set to the operation.
#[derive(Debug, Clone, PartialEq)]
pub struct ProvenanceData {
    pub sources: SmallVec<[CsgSource; 1]>,
    pub last_op: Option<OpType>,
}

impl ProvenanceData {
    /// Convenience constructor for a face that comes directly from a single CSG
    /// primitive (the common case).
    pub fn primitive(prov_id: u64, geom_id: u64) -> Self {
        Self {
            sources: SmallVec::from_buf([CsgSource::new(prov_id, geom_id)]),
            last_op: None,
        }
    }
}

/// Kernel-wide tolerance: a single global *relative* tolerance with an absolute
/// floor, applied against local feature size. See `architecture/architecture.md`.
///
/// `eps_rel` is dimensionless and covers both positions and orientations.
/// `abs_floor` is a **minimum reference scale** (a denormal/underflow guard), not
/// a minimum snap distance: the effective minimum comparison distance is
/// `eps_rel * abs_floor`. Not stored per-node — all operations in a context share
/// one tolerance.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Tolerance {
    /// Relative tolerance (dimensionless), applied to a call-site `ref_scale`.
    pub eps_rel: f64,
    /// Minimum reference scale; reference scales below this are clamped to it.
    pub abs_floor: f64,
}

impl Default for Tolerance {
    fn default() -> Self {
        Self {
            eps_rel: 1e-10,
            abs_floor: 1e-12,
        }
    }
}

/// Tolerance-aware scalar equality: `|a - b| <= eps_rel * max(ref_scale, abs_floor)`.
///
/// `ref_scale` is the *local feature size* at the call site (edge length, bbox
/// diagonal, …), not a raw coordinate magnitude. See `architecture/architecture.md`.
pub fn fuzzy_eq(a: f64, b: f64, ref_scale: f64, tol: &Tolerance) -> bool {
    (a - b).abs() <= tol.eps_rel * ref_scale.max(tol.abs_floor)
}

/// Angle between two vectors, in `[0, π]`, via `atan2(|u × v|, u · v)`.
///
/// This form stays well-conditioned near alignment (`θ ≈ 0`), where the
/// `acos(u · v)` route loses precision. Callers comparing orientations should
/// pass *unit* vectors.
pub fn angle_between(u: Point3, v: Point3) -> f64 {
    u.cross(v).length().atan2(u.dot(v))
}

/// Tolerance-aware orientation equality for *unit* vectors `u`, `v`.
///
/// `true` iff the angle between them is within `tol.eps_rel` (the tolerance for
/// orientations uses `ref_scale = 1`). A near-zero-length vector is a degeneracy
/// to handle explicitly, not via tolerance.
pub fn fuzzy_angle_eq(u: Point3, v: Point3, tol: &Tolerance) -> bool {
    angle_between(u, v) <= tol.eps_rel
}

// ── Topological structs ───────────────────────────────────────────────────────

/// A geometric vertex: a 3-D point.
///
/// Per-vertex tolerance is deliberately absent (see `architecture.md`: the
/// OpenCASCADE-style per-entity tolerance is rejected in favour of one global
/// relative tolerance on the `Context`).
#[derive(Debug, Clone, PartialEq)]
pub struct Vertex {
    pub point: Point3,
}

impl Vertex {
    pub fn new(point: Point3) -> Self {
        Self { point }
    }
}

/// A trimmed curve connecting two vertices.
///
/// A manifold edge has exactly two coedges (one per adjacent face); during boolean
/// intermediate steps more than two may be present temporarily. Coedge incidence is
/// convenience data and lives in `Context::coedges_of_edge`.
///
/// Degenerate edges (`v0 == v1`, curve evaluates to a constant point) represent the
/// poles of a sphere or the apex of a cone. See `brep_notes.md`.
#[derive(Debug, Clone, PartialEq)]
pub struct Edge {
    pub curve3: Curve3Id,
    pub v0: VertexId,
    pub v1: VertexId,
    /// Parameter value such that `curve3.eval(t0)` gives the position of `v0`.
    pub t0: f64,
    /// Parameter value such that `curve3.eval(t1)` gives the position of `v1`.
    pub t1: f64,
}

impl Edge {
    pub fn new(curve3: Curve3Id, v0: VertexId, v1: VertexId, t0: f64, t1: f64) -> Self {
        Self {
            curve3,
            v0,
            v1,
            t0,
            t1,
        }
    }
}

/// An oriented use of an [`Edge`] by a [`Face`].
///
/// The `pcurve` is the image of this coedge in the UV parameter space of the containing
/// face's surface. Its orientation matches the 3-D curve: if `orientation` is `Forward`,
/// the pcurve runs in the direction of increasing `t`.
/// The containing face is convenience data (`Context::face_of_coedge`).
#[derive(Debug, Clone, PartialEq)]
pub struct CoEdge {
    pub edge: EdgeId,
    pub orientation: Orientation,
    pub pcurve: Curve2Id,
}

impl CoEdge {
    pub fn new(edge: EdgeId, orientation: Orientation, pcurve: Curve2Id) -> Self {
        Self {
            edge,
            orientation,
            pcurve,
        }
    }
}

/// An ordered, closed sequence of [`CoEdge`]s bounding a region of a [`Face`].
///
/// `coedges` starts empty and is populated in order; the invariant is that the end
/// vertex of each coedge equals the start vertex of the next, and the last coedge's end
/// equals the first's start.
/// The containing face is convenience data (`Context::face_of_loop`).
#[derive(Debug, Clone, PartialEq)]
pub struct Loop {
    pub coedges: Vec<CoEdgeId>,
    pub is_outer: bool,
}

impl Loop {
    pub fn new(is_outer: bool) -> Self {
        Self {
            coedges: Vec::new(),
            is_outer,
        }
    }
}

/// A trimmed parametric surface bounded by one outer loop and zero or more inner loops
/// (holes).
///
/// `attr` is `None` at construction and may be set later to attach colour/material data.
/// The containing shell is convenience data (`Context::shell_of_face`).
#[derive(Debug, Clone, PartialEq)]
pub struct Face {
    pub surface: SurfaceId,
    pub outer: LoopId,
    pub inners: Vec<LoopId>,
    pub sense: FaceSense,
    pub prov: ProvenanceData,
    pub attr: Option<AttrId>,
}

impl Face {
    pub fn new(surface: SurfaceId, outer: LoopId, sense: FaceSense, prov: ProvenanceData) -> Self {
        Self {
            surface,
            outer,
            inners: Vec::new(),
            sense,
            prov,
            attr: None,
        }
    }
}

/// A connected, orientable collection of [`Face`]s forming a single closed surface.
///
/// `faces` starts empty and is populated as faces are added to the B-rep.
/// The containing solid is convenience data (`Context::solid_of_shell`).
#[derive(Debug, Clone, PartialEq)]
pub struct Shell {
    pub faces: Vec<FaceId>,
    pub is_outer: bool,
}

impl Shell {
    pub fn new(is_outer: bool) -> Self {
        Self {
            faces: Vec::new(),
            is_outer,
        }
    }
}

/// A single connected solid: one outer shell and zero or more inner shells (voids).
#[derive(Debug, Clone, PartialEq)]
pub struct Solid {
    pub outer: ShellId,
    pub inners: Vec<ShellId>,
}

impl Solid {
    pub fn new(outer: ShellId) -> Self {
        Self {
            outer,
            inners: Vec::new(),
        }
    }
}

/// The B-rep result of evaluating a single CSG node.
///
/// A CSG node may produce zero solids (empty result) or more than one (disconnected
/// components from a boolean operation). `solids` starts empty and is populated during
/// B-rep compilation.
#[derive(Debug, Clone, PartialEq)]
pub struct SolidSet {
    pub solids: Vec<SolidId>,
    pub source_csg_id: u64,
}

impl SolidSet {
    pub fn new(source_csg_id: u64) -> Self {
        Self {
            solids: Vec::new(),
            source_csg_id,
        }
    }
}

// ── Arena macro ───────────────────────────────────────────────────────────────

/// Generate `push_<name>`, `get_<name>`, and `get_mut_<name>` methods on
/// `SolidModelingContext` for one entity type.
macro_rules! impl_push_get {
    ($vec:ident, $id:ident, $item:ty, $push:ident, $get:ident, $get_mut:ident) => {
        pub fn $push(&mut self, item: $item) -> $id {
            let id = $id(self.$vec.len());
            self.$vec.push(item);
            id
        }
        pub fn $get(&self, id: $id) -> &$item {
            &self.$vec[id.0]
        }
        pub fn $get_mut(&mut self, id: $id) -> &mut $item {
            &mut self.$vec[id.0]
        }
    };
}

// ── SolidModelingContext ──────────────────────────────────────────────────────

/// The central arena that owns all B-rep entities.
///
/// All geometry and topology is stored in typed `Vec`s. Entity IDs are indices into
/// these `Vec`s and remain stable as long as no element is removed. Operations within
/// the context share a single [`Tolerance`].
pub struct SolidModelingContext {
    pub surfaces: Vec<SurfaceKind>,
    pub curves3: Vec<Curve3Kind>,
    pub curves2: Vec<Curve2Kind>,
    pub solidsets: Vec<SolidSet>,
    pub solids: Vec<Solid>,
    pub shells: Vec<Shell>,
    pub faces: Vec<Face>,
    pub loops: Vec<Loop>,
    pub coedges: Vec<CoEdge>,
    pub edges: Vec<Edge>,
    pub vertices: Vec<Vertex>,
    pub attributes: Vec<Arc<CsgMetadata>>,
    // ── Derived side-tables (convenience refs; rebuilt by `rebuild_indices`) ──
    // These may be stale during a topological mutation. Ops that need them must
    // call `rebuild_indices` first, or read defining content directly.
    pub shell_by_face: HashMap<FaceId, ShellId>,
    pub solid_by_shell: HashMap<ShellId, SolidId>,
    pub solidset_by_solid: HashMap<SolidId, SolidSetId>,
    pub coedges_by_edge: HashMap<EdgeId, Vec<CoEdgeId>>,
    pub faces_by_edge: HashMap<EdgeId, Vec<FaceId>>,
    pub face_by_coedge: HashMap<CoEdgeId, FaceId>,
    pub face_by_loop: HashMap<LoopId, FaceId>,
    pub edges_by_shell: HashMap<ShellId, Vec<EdgeId>>,
    pub vertices_by_shell: HashMap<ShellId, Vec<VertexId>>,
    pub tolerance: Tolerance,
}

impl SolidModelingContext {
    /// Create an empty context with default kernel tolerances.
    pub fn new() -> Self {
        Self {
            surfaces: Vec::new(),
            curves3: Vec::new(),
            curves2: Vec::new(),
            solidsets: Vec::new(),
            solids: Vec::new(),
            shells: Vec::new(),
            faces: Vec::new(),
            loops: Vec::new(),
            coedges: Vec::new(),
            edges: Vec::new(),
            vertices: Vec::new(),
            attributes: Vec::new(),
            shell_by_face: HashMap::new(),
            solid_by_shell: HashMap::new(),
            solidset_by_solid: HashMap::new(),
            coedges_by_edge: HashMap::new(),
            faces_by_edge: HashMap::new(),
            face_by_coedge: HashMap::new(),
            face_by_loop: HashMap::new(),
            edges_by_shell: HashMap::new(),
            vertices_by_shell: HashMap::new(),
            tolerance: Tolerance::default(),
        }
    }

    impl_push_get!(
        surfaces,
        SurfaceId,
        SurfaceKind,
        push_surface,
        get_surface,
        get_mut_surface
    );
    impl_push_get!(
        curves3,
        Curve3Id,
        Curve3Kind,
        push_curve3,
        get_curve3,
        get_mut_curve3
    );
    impl_push_get!(
        curves2,
        Curve2Id,
        Curve2Kind,
        push_curve2,
        get_curve2,
        get_mut_curve2
    );
    impl_push_get!(
        solidsets,
        SolidSetId,
        SolidSet,
        push_solidset,
        get_solidset,
        get_mut_solidset
    );
    impl_push_get!(solids, SolidId, Solid, push_solid, get_solid, get_mut_solid);
    impl_push_get!(shells, ShellId, Shell, push_shell, get_shell, get_mut_shell);
    impl_push_get!(faces, FaceId, Face, push_face, get_face, get_mut_face);
    impl_push_get!(loops, LoopId, Loop, push_loop, get_loop, get_mut_loop);
    impl_push_get!(
        coedges,
        CoEdgeId,
        CoEdge,
        push_coedge,
        get_coedge,
        get_mut_coedge
    );
    impl_push_get!(edges, EdgeId, Edge, push_edge, get_edge, get_mut_edge);
    impl_push_get!(
        vertices,
        VertexId,
        Vertex,
        push_vertex,
        get_vertex,
        get_mut_vertex
    );
    impl_push_get!(
        attributes,
        AttrId,
        Arc<CsgMetadata>,
        push_attr,
        get_attr,
        get_mut_attr
    );

    // ── Derived side-table accessors ───────────────────────────────────────────

    /// The shell that owns `face`, or `None` if not yet indexed.
    pub fn shell_of_face(&self, face: FaceId) -> Option<ShellId> {
        self.shell_by_face.get(&face).copied()
    }

    /// The solid that owns `shell`, or `None` if not yet indexed.
    pub fn solid_of_shell(&self, shell: ShellId) -> Option<SolidId> {
        self.solid_by_shell.get(&shell).copied()
    }

    /// The solid set that lists `solid`, or `None` if not yet indexed.
    pub fn solidset_of_solid(&self, solid: SolidId) -> Option<SolidSetId> {
        self.solidset_by_solid.get(&solid).copied()
    }

    /// The coedges incident to `edge`, in arena (creation) order.
    pub fn coedges_of_edge(&self, edge: EdgeId) -> &[CoEdgeId] {
        self.coedges_by_edge.get(&edge).map_or(&[], Vec::as_slice)
    }

    /// The (distinct) faces incident to `edge`, in coedge arena order.
    pub fn faces_of_edge(&self, edge: EdgeId) -> &[FaceId] {
        self.faces_by_edge.get(&edge).map_or(&[], Vec::as_slice)
    }

    /// The face that owns `coedge`, or `None` if not yet indexed.
    pub fn face_of_coedge(&self, coedge: CoEdgeId) -> Option<FaceId> {
        self.face_by_coedge.get(&coedge).copied()
    }

    /// The face that owns `lp`, or `None` if not yet indexed.
    pub fn face_of_loop(&self, lp: LoopId) -> Option<FaceId> {
        self.face_by_loop.get(&lp).copied()
    }

    /// The edges bounding `shell`, in first-seen face/loop order.
    pub fn edges_of_shell(&self, shell: ShellId) -> &[EdgeId] {
        self.edges_by_shell.get(&shell).map_or(&[], Vec::as_slice)
    }

    /// The vertices bounding `shell`, in first-seen face/loop order.
    pub fn vertices_of_shell(&self, shell: ShellId) -> &[VertexId] {
        self.vertices_by_shell
            .get(&shell)
            .map_or(&[], Vec::as_slice)
    }

    /// The faces bounding `shell` (defining data, read directly from the shell).
    pub fn faces_of_shell(&self, shell: ShellId) -> &[FaceId] {
        &self.shells[shell.0].faces
    }

    /// Rebuild every derived side-table from the defining b-rep content.
    ///
    /// Call once after any topological mutation. Side-tables may be stale
    /// *during* a mutating op; ops that need them must call this first or read
    /// defining content directly.
    pub fn rebuild_indices(&mut self) {
        self.shell_by_face.clear();
        self.solid_by_shell.clear();
        self.solidset_by_solid.clear();
        self.coedges_by_edge.clear();
        self.faces_by_edge.clear();
        self.face_by_coedge.clear();
        self.face_by_loop.clear();
        self.edges_by_shell.clear();
        self.vertices_by_shell.clear();

        // SolidSet -> Solid
        for (i, set) in self.solidsets.iter().enumerate() {
            for &sid in &set.solids {
                self.solidset_by_solid.insert(sid, SolidSetId(i));
            }
        }

        // Solid -> Shell
        for (i, solid) in self.solids.iter().enumerate() {
            let sid = SolidId(i);
            self.solid_by_shell.insert(solid.outer, sid);
            for &inner in &solid.inners {
                self.solid_by_shell.insert(inner, sid);
            }
        }

        // CoEdge -> Edge (arena order preserves creation order).
        for (i, ce) in self.coedges.iter().enumerate() {
            self.coedges_by_edge
                .entry(ce.edge)
                .or_default()
                .push(CoEdgeId(i));
        }

        // Shell -> Face / Face -> Shell, Loop -> Face, CoEdge -> Face, shell edge/vertex sets.
        for (i, shell) in self.shells.iter().enumerate() {
            let shell_id = ShellId(i);
            let mut edges: Vec<EdgeId> = Vec::new();
            let mut verts: Vec<VertexId> = Vec::new();
            for &face_id in &shell.faces {
                self.shell_by_face.insert(face_id, shell_id);
                let face = &self.faces[face_id.0];
                let mut loops = Vec::with_capacity(1 + face.inners.len());
                loops.push(face.outer);
                loops.extend_from_slice(&face.inners);
                for lp in loops {
                    self.face_by_loop.insert(lp, face_id);
                    for &ce_id in &self.loops[lp.0].coedges {
                        self.face_by_coedge.insert(ce_id, face_id);
                        let edge_id = self.coedges[ce_id.0].edge;
                        if !edges.contains(&edge_id) {
                            edges.push(edge_id);
                        }
                        let edge = &self.edges[edge_id.0];
                        if !verts.contains(&edge.v0) {
                            verts.push(edge.v0);
                        }
                        if !verts.contains(&edge.v1) {
                            verts.push(edge.v1);
                        }
                    }
                }
            }
            self.edges_by_shell.insert(shell_id, edges);
            self.vertices_by_shell.insert(shell_id, verts);
        }

        // Edge -> Face (derived from CoEdge -> Face).
        for (i, ce) in self.coedges.iter().enumerate() {
            if let Some(&face_id) = self.face_by_coedge.get(&CoEdgeId(i)) {
                let v = self.faces_by_edge.entry(ce.edge).or_default();
                if !v.contains(&face_id) {
                    v.push(face_id);
                }
            }
        }
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod test {
    use super::*;
    use crate::geom::{Curve3Kind, Line3, Plane, Point3, SurfaceKind};

    fn pt(x: f64, y: f64, z: f64) -> Point3 {
        Point3::new(x, y, z)
    }

    fn minimal_ctx() -> SolidModelingContext {
        SolidModelingContext::new()
    }

    // ── Newtype IDs ───────────────────────────────────────────────────────────

    #[test]
    fn id_equality() {
        assert_eq!(VertexId(0), VertexId(0));
        assert_ne!(VertexId(0), VertexId(1));
    }

    #[test]
    fn id_copy() {
        let a = EdgeId(3);
        let b = a; // Copy — both remain valid
        assert_eq!(a, b);
    }

    // ── Support types ─────────────────────────────────────────────────────────

    #[test]
    fn face_sense_eq() {
        assert_eq!(FaceSense::Aligned, FaceSense::Aligned);
        assert_ne!(FaceSense::Aligned, FaceSense::AntiAligned);
    }

    #[test]
    fn orientation_eq() {
        assert_eq!(Orientation::Forward, Orientation::Forward);
        assert_ne!(Orientation::Forward, Orientation::Reverse);
    }

    #[test]
    fn op_type_eq() {
        assert_eq!(OpType::Union, OpType::Union);
        assert_ne!(OpType::Union, OpType::Difference);
    }

    #[test]
    fn csg_source_stores_fields() {
        let s = CsgSource::new(42, 99);
        assert_eq!(s.prov_id, 42);
        assert_eq!(s.geom_id, 99);
    }

    #[test]
    fn provenance_primitive_one_source_no_op() {
        let prov = ProvenanceData::primitive(1, 2);
        assert_eq!(prov.sources.len(), 1);
        assert_eq!(prov.sources[0].prov_id, 1);
        assert_eq!(prov.sources[0].geom_id, 2);
        assert_eq!(prov.last_op, None);
    }

    #[test]
    fn tolerance_defaults() {
        let t = Tolerance::default();
        assert_eq!(t.eps_rel, 1e-10);
        assert_eq!(t.abs_floor, 1e-12);
    }

    #[test]
    fn fuzzy_eq_relative_to_ref_scale() {
        let t = Tolerance::default();
        // Within eps_rel * ref_scale (ref_scale = 1).
        assert!(fuzzy_eq(1.0, 1.0 + 1e-11, 1.0, &t));
        // Outside: a 1% difference is far beyond 1e-10.
        assert!(!fuzzy_eq(1.0, 1.01, 1.0, &t));
        // Larger ref_scale loosens the threshold proportionally.
        assert!(fuzzy_eq(0.0, 1e-5, 1e6, &t));
        assert!(!fuzzy_eq(0.0, 1e-5, 1e4, &t));
    }

    #[test]
    fn fuzzy_eq_abs_floor_is_a_minimum_scale() {
        let t = Tolerance::default();
        // Option A: threshold = eps_rel * max(ref_scale, abs_floor). At a tiny
        // ref_scale the multiplier is clamped to abs_floor, so the distance
        // threshold is eps_rel * abs_floor = 1e-22 -- NOT abs_floor itself.
        assert!(fuzzy_eq(0.0, 0.5e-22, 0.0, &t));
        assert!(!fuzzy_eq(0.0, 2e-22, 0.0, &t));
        // A non-zero ref_scale below the floor yields the same threshold.
        assert!(fuzzy_eq(0.0, 0.5e-22, 1e-15, &t));
        assert!(!fuzzy_eq(0.0, 2e-22, 1e-15, &t));
    }

    #[test]
    fn fuzzy_angle_eq_well_conditioned_near_alignment() {
        let t = Tolerance::default();
        let u = Point3::new(1.0, 0.0, 0.0);
        // A ~1e-12 rad tilt is well within eps_rel (atan2 form stays accurate).
        let v = Point3::new(1.0, 1e-12, 0.0).normalize();
        assert!(fuzzy_angle_eq(u, v, &t));
        // 90 degrees is far outside.
        assert!(!fuzzy_angle_eq(u, Point3::new(0.0, 1.0, 0.0), &t));
        // Anti-aligned (pi) is far outside.
        assert!(!fuzzy_angle_eq(u, Point3::new(-1.0, 0.0, 0.0), &t));
    }

    // ── Topological struct construction ───────────────────────────────────────

    #[test]
    fn vertex_new_stores_point() {
        let v = Vertex::new(pt(1.0, 2.0, 3.0));
        assert_eq!(v.point, pt(1.0, 2.0, 3.0));
    }

    #[test]
    fn edge_new_stores_fields() {
        let e = Edge::new(Curve3Id(0), VertexId(0), VertexId(1), 0.0, 1.0);
        assert_eq!(e.curve3, Curve3Id(0));
        assert_eq!(e.v0, VertexId(0));
        assert_eq!(e.v1, VertexId(1));
        assert_eq!(e.t0, 0.0);
        assert_eq!(e.t1, 1.0);
    }

    #[test]
    fn coedge_new_stores_fields() {
        let ce = CoEdge::new(EdgeId(0), Orientation::Forward, Curve2Id(0));
        assert_eq!(ce.edge, EdgeId(0));
        assert_eq!(ce.orientation, Orientation::Forward);
        assert_eq!(ce.pcurve, Curve2Id(0));
    }

    #[test]
    fn loop_new_stores_fields_coedges_empty() {
        let l = Loop::new(true);
        assert!(l.is_outer);
        assert!(l.coedges.is_empty());
    }

    #[test]
    fn face_new_stores_fields_inners_empty_attr_none() {
        let prov = ProvenanceData::primitive(1, 2);
        let f = Face::new(SurfaceId(0), LoopId(0), FaceSense::Aligned, prov.clone());
        assert_eq!(f.surface, SurfaceId(0));
        assert_eq!(f.outer, LoopId(0));
        assert_eq!(f.sense, FaceSense::Aligned);
        assert_eq!(f.prov, prov);
        assert!(f.inners.is_empty());
        assert!(f.attr.is_none());
    }

    #[test]
    fn shell_new_stores_fields_faces_empty() {
        let s = Shell::new(true);
        assert!(s.is_outer);
        assert!(s.faces.is_empty());
    }

    #[test]
    fn solid_new_stores_outer_inners_empty() {
        let s = Solid::new(ShellId(0));
        assert_eq!(s.outer, ShellId(0));
        assert!(s.inners.is_empty());
    }

    #[test]
    fn solidset_new_stores_csg_id_solids_empty() {
        let n = SolidSet::new(42);
        assert_eq!(n.source_csg_id, 42);
        assert!(n.solids.is_empty());
    }

    // ── Arena round-trips ─────────────────────────────────────────────────────

    #[test]
    fn arena_vertex_push_get_roundtrip() {
        let mut ctx = minimal_ctx();
        let id0 = ctx.push_vertex(Vertex::new(pt(0.0, 0.0, 0.0)));
        let id1 = ctx.push_vertex(Vertex::new(pt(1.0, 0.0, 0.0)));
        assert_eq!(id0, VertexId(0));
        assert_eq!(id1, VertexId(1));
        assert_eq!(ctx.get_vertex(id0).point, pt(0.0, 0.0, 0.0));
        assert_eq!(ctx.get_vertex(id1).point, pt(1.0, 0.0, 0.0));
    }

    #[test]
    fn arena_vertex_get_mut_modifies() {
        let mut ctx = minimal_ctx();
        let id = ctx.push_vertex(Vertex::new(pt(0.0, 0.0, 0.0)));
        ctx.get_mut_vertex(id).point = pt(9.0, 9.0, 9.0);
        assert_eq!(ctx.get_vertex(id).point, pt(9.0, 9.0, 9.0));
    }

    #[test]
    fn arena_edge_push_get_roundtrip() {
        let mut ctx = minimal_ctx();
        let id = ctx.push_edge(Edge::new(Curve3Id(0), VertexId(0), VertexId(1), 0.0, 1.0));
        assert_eq!(id, EdgeId(0));
        assert_eq!(ctx.get_edge(id).v1, VertexId(1));
    }

    #[test]
    fn arena_face_push_get_roundtrip() {
        let mut ctx = minimal_ctx();
        let prov = ProvenanceData::primitive(1, 2);
        let id = ctx.push_face(Face::new(
            SurfaceId(0),
            LoopId(0),
            FaceSense::AntiAligned,
            prov,
        ));
        assert_eq!(id, FaceId(0));
        assert_eq!(ctx.get_face(id).sense, FaceSense::AntiAligned);
    }

    #[test]
    fn arena_surface_push_get_roundtrip() {
        let mut ctx = minimal_ctx();
        let plane = Plane::new(pt(0.0, 0.0, 0.0), pt(1.0, 0.0, 0.0), pt(0.0, 1.0, 0.0));
        let id = ctx.push_surface(SurfaceKind::Plane(plane));
        assert_eq!(id, SurfaceId(0));
        // Verify it round-trips: can get_surface without panic
        let _ = ctx.get_surface(id);
    }

    #[test]
    fn arena_curve3_push_get_roundtrip() {
        let mut ctx = minimal_ctx();
        let line = Line3::new(pt(0.0, 0.0, 0.0), pt(1.0, 0.0, 0.0));
        let id = ctx.push_curve3(Curve3Kind::Line3(line));
        assert_eq!(id, Curve3Id(0));
        let _ = ctx.get_curve3(id);
    }

    #[test]
    fn arena_ids_increment_per_type() {
        let mut ctx = minimal_ctx();
        let v0 = ctx.push_vertex(Vertex::new(pt(0.0, 0.0, 0.0)));
        let v1 = ctx.push_vertex(Vertex::new(pt(1.0, 0.0, 0.0)));
        let e0 = ctx.push_edge(Edge::new(Curve3Id(0), v0, v1, 0.0, 1.0));
        let e1 = ctx.push_edge(Edge::new(Curve3Id(0), v0, v1, 0.0, 1.0));
        // Vertex and Edge IDs are independent sequences
        assert_eq!(v0, VertexId(0));
        assert_eq!(v1, VertexId(1));
        assert_eq!(e0, EdgeId(0));
        assert_eq!(e1, EdgeId(1));
    }
}
