# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "Node",
    "cone",
    "cuboid",
    "cylinder",
    "difference",
    "intersection",
    "select_closest_to",
    "select_contains",
    "select_largest",
    "sphere",
    "union",
]

@typing.final
class Node:
    r"""
    A CSG node: a primitive or operation with an associated transform stack.
    
    Create nodes with the module-level constructors (`sphere`, `cuboid`, etc.)
    and chain transforms with the methods below. All transform methods return
    a **new** Node; the original is never mutated.
    """
    @property
    def prov_id(self) -> builtins.int:
        r"""
        Unique provenance ID for this node (assigned at construction time).
        """
    @property
    def geom_id(self) -> builtins.int:
        r"""
        Geometry hash: equal for structurally identical shapes regardless of
        authoring order or Arc identity.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def translate(self, dx: builtins.float, dy: builtins.float, dz: builtins.float) -> Node:
        r"""
        Return a new Node translated by (dx, dy, dz).
        """
    def scale(self, sx: builtins.float, sy: builtins.float, sz: builtins.float) -> Node:
        r"""
        Return a new Node scaled by (sx, sy, sz).
        """
    def rot_x(self, angle_rad: builtins.float) -> Node:
        r"""
        Return a new Node rotated around the X axis by `angle_rad` (right-hand rule).
        """
    def rot_y(self, angle_rad: builtins.float) -> Node:
        r"""
        Return a new Node rotated around the Y axis by `angle_rad` (right-hand rule).
        """
    def rot_z(self, angle_rad: builtins.float) -> Node:
        r"""
        Return a new Node rotated around the Z axis by `angle_rad` (right-hand rule).
        """
    def rot_aa(self, axis: typing.Sequence[builtins.float], angle_rad: builtins.float) -> Node:
        r"""
        Return a new Node rotated around `axis` by `angle_rad` (right-hand rule).
        
        Args:
            axis: Rotation axis as `[x, y, z]`. Need not be a unit vector; normalised internally.
            angle_rad: Rotation angle in radians.
        """

def cone(r: builtins.float, h: builtins.float) -> Node:
    r"""
    Create a cone with base radius `r` and height `h`.
    The base circle lies in the z = 0 plane centered at the origin; the apex is at z = h.
    """

def cuboid(dx: builtins.float, dy: builtins.float, dz: builtins.float) -> Node:
    r"""
    Create an axis-aligned cuboid with one corner at the origin and the opposite corner at `(dx, dy, dz)`.
    """

def cylinder(r: builtins.float, h: builtins.float) -> Node:
    r"""
    Create a cylinder with radius `r` and height `h`.
    The base circle lies in the z = 0 plane centered at the origin; the top is at z = h.
    """

def difference(base: Node, *subtract: typing.Any) -> Node:
    r"""
    Subtract volumes from a base shape: `difference(base, sub1, sub2, ...)`.
    
    Raises `ValueError` if no subtracted nodes are provided.
    """

def intersection(*children: typing.Any) -> Node:
    r"""
    Return the intersection (common volume) of the given nodes: `intersection(a, b, c, ...)`.
    
    Raises `ValueError` if no nodes are provided.
    """

def select_closest_to(node: Node, point: typing.Sequence[builtins.float]) -> Node:
    r"""
    Select the connected component of `node` whose centroid is closest to `point`.
    `point` is a 3-element sequence `[x, y, z]`.
    """

def select_contains(node: Node, point: typing.Sequence[builtins.float]) -> Node:
    r"""
    Select the connected component of `node` that contains `point`.
    `point` is a 3-element sequence `[x, y, z]`.
    """

def select_largest(node: Node) -> Node:
    r"""
    Select the single largest connected component of `node` by volume.
    """

def sphere(r: builtins.float) -> Node:
    r"""
    Create a sphere with radius `r`, centered at the origin.
    """

def union(*children: typing.Any) -> Node:
    r"""
    Return the boolean union of the given nodes: `union(a, b, c, ...)`.
    
    Raises `ValueError` if no nodes are provided.
    """

